# Kadam Smit Rajkumar

📧 smitkadamele@gmail.com  
📞 +91-8888302003  
[![LinkedIn](https://img.shields.io/badge/LinkedIn-Connect-blue)](https://www.linkedin.com/in/yourprofile)

## Career Objective

Dedicated professional aiming for career enhancement opportunities in Industrial Automation domain with an organization of high repute, preferably in the Projects industry.

## Professional Summary

- Schematic drawing preparation, monitored control panel manufacturing, and testing operations to consistently meet rigorous customer requirements.
- Expertise in developing quality assurance documentation, including protocols, qualification documents, design systems, test plans, and test reports.
- Strong capability in PLC, Relay, PCC, and MCC panel design using EPLAN and AutoCAD.
- Control panel design and integration for BIW line.
- Experience in creating Bills of Materials, designing panel layouts using EPLAN and AutoCAD (2D), and developing electrical wiring designs.
- Preparation of Single Line Diagram, Layout, Design Review Documents, Earthing, CT & PT Sizing Calculation, Cable Sizing and Calculation.
- Proven leadership skills in supervising project activities, managing the entire project lifecycle, and implementing effective documentation and workflow techniques.
- Design of electrical panels in low voltage.
- Delivering detailed engineering design with precision and expertise.
- Successfully managed cross-cultural projects for prototype development and electrical schematics, adhering to international standards (IEC/UL/NEMA) in locations like France and Italy.
- Extensive experience in electrical control panel design and manufacturing, ensuring adherence to rigorous customer requirements and international safety standards (CE, MD, LVD, EMC).
- Proficiency in applying machine safety principles (EN ISO 13849-1/-2, EN 61800-5-2) to create safe and reliable control systems.

## Work Experience

### Sr. Electrical Design Engineer
**Sidel India Pvt. Ltd.**  
*October 2022 – Present*  
- Lead electrical design projects from concept to completion, overseeing planning, implementation, coordination, and progress monitoring.
- Collaborate with sales engineers to develop project schemes that meet customer needs.
- Ensure design quality by reviewing and approving team member work.
- Create and maintain technical documentation (calculations, BOMs, schematics).

### Business Analyst (Electrical Design)
**Genpact India Pvt. Ltd.**  
*March 2021 – October 2022*  
- Managed the electrical design process, including estimations, planning, and project oversight.
- Contributed to project concept development and collaborated with sales engineers on project proposals.
- Supervised project execution and troubleshooting for assigned projects.
- Prepared technical documentation (introductions and service procedures).

### Sr. Electrical Engineer
**Profesyst Consulting Services Pvt. Ltd.**  
*August 2019 – March 2021*  
- Led and performed new product electrical design tasks, including planning, implementation, coordination, and progress monitoring.
- Developed project concepts and reviewed team member designs.
- Partnered with sales engineers on project proposals.
- Supervised project execution and troubleshooting.
- Created technical documentation (introductions and service procedures).

### Electrical Engineer – Design
**Aichelin Unitherm Heat Treatment Systems India Pvt. Ltd.**  
*February 2019 – August 2019*  
- Responsible for new product electrical design process, including planning, implementation, coordination, and progress monitoring.
- Responsible for project concepts in electrical parts.
- Checked and confirmed design programs of team members.
- Collaborated on project schemes with sales engineers.
- Supervised fixing and debugging of relevant projects.
- Maintained relevant technical documents for responsible projects.

### Project Engineer
**Dhruva Automation & Controls Pvt. Ltd.**  
*October 2017 – February 2019*  
- Identified system requirements and decided on the type and components of panels.
- Prepared design and BOM, took client approval, and inspected manufacturing.
- Tested the system.

### Trainee Engineer
**M/S Uttam Electrical and Engineering Services, Nanded**  
*July 2015 - December 2016*  
- Monitored installation and operations to consistently meet rigorous customer requirements.
- Designed panels as per requirements.
- Maintained records of work status and billing.
- Oversaw transformer installation and battery maintenance.
- Inspected work as per design diagrams.

## Technical Skills

- Control Panel Design in EPLAN and AutoCAD
- Automotive Wire Harness in CATIA
- PLC Automation System Logic Development and Programming

## Major Projects Executed

### Indo Schöttle Auto Parts Heat Treatment Plant
- **Project Site:** INDO SCHÖTTLE PIRANGUT
- **Client:** Indo Schöttle Auto Parts Pvt. Ltd.
- **Role:** Electrical design process, including planning, implementation, coordination, and progress monitoring.

### TATA Q5 Body Shop
- **Project Site:** TATA MOTORS, PIMPRI
- **Client:** COMAU India Pvt. Ltd.
- **Role:** Designed layout of Panel using Electrical wiring Design using EPLAN p8 2.4, Panel Testing.

### ALSTOM Rail Coach Assembly/Testing Project
- **Project Site:** O.L.C.I. Chakan
- **Client:** O.L.C.I. India Pvt. Ltd.
- **Role:** Designed layout of Panel using Electrical wiring Design using EPLAN p8 2.4, Panel Testing.

### Paint Shop Conveyor Systems
- **Project Site:** Enkei Wheels India Ltd, Shikrapur
- **Client:** Eisenmann India Pvt. Ltd.
- **Role:** Bill of Material, Designed layout of Panel using Electrical wiring Design using EPLAN p8 2.4, Panel Testing.

### PCC Panel
- **Project Site:** Saisidha Sugar Equ. & Engg. Co. Pvt. Ltd.
- **Client:** Saisidha Sugar Equ. & Engg. Co. Pvt. Ltd.
- **Role:** Bill of Material, Designed layout of Panel using Electrical wiring Design using EPLAN p8 2.4, Panel Testing.

### ICAD Main Controller Panel
- **Project Site:** Skovlytoften 33, Denmark
- **Client:** Flatworld Solutions
- **Role:** Bill of Material, Designed layout of Panel using Electrical wiring Design using AutoCAD.

## Certifications

- Research paper published on ‘Lean manufacturing technique in industrial automation’.
- In Plant Training: E.H.V. (O&M) Substation Jangamwadi, Nanded.
- Certificate by Heat Spring in Residential Solar PV Project Management Gantt Chart.
- Prize-winning performance certificate in line follower robot competition.
- Authorized certification by PWD Department of Maharashtra state government as an electrical supervisor.
- Certificate in Microprocessor Programming Workshop.
- Certificate of Computer Learning CCC and AutoCAD.

## Academic Qualifications

- **MBA Master of Business Administration** (2017-2019) with 65% from P.K. Technical Campus, Chakan S.P.P.U. University.
- **B.E. Electrical and Electronics Engineering** (2013-16) with 65% from MIT Aurangabad, B.A.M.U. University.
- **Diploma in Electrical Engineering** (2010-12) with 66.17% from IIT Nanded, M.S.B.T.E.
- **SSC** (2008-2009) with 75% from Rajarshri Shahu Vidyalaya, Nanded.

## Achievements and Extra-Curricular Activities

- Seminar on E-Waste and Energy Efficient Transformer.

## Personal Details

- **Date of Birth:** 07th July 1993
- **Father's Name:** Shri Rajkumar Kadam
- **Marital Status:** Married
- **Gender:** Male
- **Languages Known:** English, Marathi, German, and Hindi
